import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.5/samples
 */

plugins {
    java apply true
    kotlin("jvm") version "1.6.21" apply true
    kotlin("plugin.spring") version "1.6.21" apply true
    kotlin("plugin.jpa") version "1.6.21" apply true
    id("org.springframework.boot") version "2.7.1" apply true
    id("io.spring.dependency-management") version "1.0.11.RELEASE" apply true
}



allprojects {

    group = "com.karohani.springframework.kotlin.learingtest"
    version = "0.0.1-SNAPSHOT"

    apply {
        plugin("org.jetbrains.kotlin.jvm")
    }

    repositories {
        mavenCentral()
    }

    dependencies {
        implementation(kotlin("stdlib"))
        testImplementation("org.junit.jupiter:junit-jupiter-api:5.8.2")
        testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine")
    }

    tasks.withType<Test> {
        useJUnitPlatform()
    }

}


tasks.withType<KotlinCompile> {
    kotlinOptions {
        freeCompilerArgs = listOf("-Xjsr305=strict")
        jvmTarget = "11"
    }
}

